LD_FILE = boards/samd21x18-bootloader.ld
USB_VID = 0x0451
USB_PID = 0xE020
USB_PRODUCT = "Unofficial TI-Python Adapter"
USB_MANUFACTURER = "Texas Instruments Incorporated"

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = LONGLONG
CIRCUITPY_SMALL_BUILD = 1

CIRCUITPY_ANALOGIO = 0
CIRCUITPY_BITBANGIO = 0
CIRCUITPY_BOARD = 1
CIRCUITPY_BUSIO = 1
CIRCUITPY_DIGITALIO = 1
CIRCUITPY_NEOPIXEL_WRITE = 0
CIRCUITPY_NVM = 0
CIRCUITPY_PULSEIO = 0
CIRCUITPY_ROTARYIO = 0
CIRCUITPY_RTC = 0
CIRCUITPY_STRUCT = 0
CIRCUITPY_SUPERVISOR = 0
CIRCUITPY_TOUCHIO = 0
CIRCUITPY_USB_HID = 0
CIRCUITPY_USB_MIDI = 0

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21
