LD_FILE = boards/samd21x18-bootloader.ld
USB_VID = 0x239A
USB_PID = 0x801F
USB_PRODUCT = "Trinket M0"
USB_MANUFACTURER = "Adafruit Industries LLC"

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_SMALL_BUILD = 1

CIRCUITPY_USB_HID = 0
CIRCUITPY_USB_MIDI = 0

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21
